export enum PrivacyGatewayErrorEnum {
  MAINERROR = 'MAINERROR',
  CALLBACKIMPLEMENTATION = 'CALLBACKIMPLEMENTATION',
  WRONGCERTIFICATEID = 'WRONGCERTIFICATEID',
  SIGNATURETOOOLD = 'SIGNATURETOOOLD',
  WRONGIMPRINT = 'WRONGIMPRINT',
  JSONSCHEMA = 'JSONSCHEMA',
  WRONGMESSAGEID = 'WRONGMESSAGEID',
  WRONGJWT = 'WRONGJWT',
  NOCERTIFICATE = 'NOCERTIFICATE',
  NOTOWNERORISSUER = 'NOTOWNERORISSUER',
}
