export * from './lib/services/eventManager/eventManager';
export * from './lib/services/eventManager/types/events';
export * from './lib/services/identity/identity';
export * from './lib/services/message/instances/messageInstance';
export * from './lib/services/message/message';
export * from './lib/services/smartAsset/instances/arianeeEventInstance';
export * from './lib/services/smartAsset/instances/smartAssetInstance';
export * from './lib/services/smartAsset/smartAsset';
export * from './lib/utils/proof/errors';
export * from './lib/utils/proof/isProofValidFromLink';
export * from './lib/wallet';
import { Wallet } from './lib/wallet';
export default Wallet;
